language:
  - groovy
  - node_js

jdk:
  - oraclejdk8

sudo: false

node_js:
  - 0.10.25

cache:
  directories:
  - $HOME/.m2

before_cache:
 - bower cache clean
 - rm -rf node_modules
 - rm -rf components/bower

before_install:
  - npm install grunt-cli bower -g
  - npm install

before_script:
 - rm -rf grails/ag-plugin/.gradle
 - rm -rf /tmp/travis/bower

matrix:
  fast_finish: true

script: "./travis-build.sh"
